#WordPress challenge

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
 # volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
 # storageClassName: slow
 # selector:
  #  matchLabels:
   #   name: "wordpress-persistent-storage"
    #matchExpressions:
     # - {key: environment, operator: In, values: [dev]}