#WordPress Challenge

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wp
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp
      type: front-end
  template:
    metadata:
      labels:
        app: wp
        type: front-end
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/html"
          name: wordpress-persistent-storage
     #   envFrom:
      #    - secretRef:
       #         name: mysql-pass
        env:
           - name: WORDPRESS_DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: mysql-pass
                   key: password
           - name: WORDPRESS_DB_HOST
             value: wordpress-mysql
     
       
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-persistent-storage
     #   - name: WORDPRESS_DB_PASSWORD
      #    secret:
       #      secretName: mysql-pass
        
